### ISSUE TITLE
Ordering of media queries

### ISSUE THREAD

**Issue by JohnCashmore** [buildingblocks/grunt-combine-media-queries#1]
Add options to allow ordering of media queries, currently it only orders by min-width

**Comment by thomasdobber** [comment]
I've updated the way the media queries are ordered:

@media ( everything that does not contain 'min-width', 'min-height' , 'max-width', 'max-height' or 'print' )
@media min-width
@media min-height
@media max-width
@media max-height
@media print

Double declarations are being ordered by the first declaration ( min-( width | height ) / max-( width | height ) ). If there is already a media query with the same declaration as the first one it will be ordered straight after.

For example:

@media only screen

@media only screen and (min-width: 569px)
@media only screen and (min-width: 569px) and (max-width: 1023px)
@media only screen and (min-width: 700px)
@media only screen and (min-width: 1024px)
@media only screen and (min-width: 1024px) and (max-height: 600px)
@media only screen and (min-width: 1200px)

@media only screen and (max-width: 1023px)
@media only screen and (max-width: 720px)
@media only screen and (max-width: 568px)
@media only screen and (max-width: 360px)

@media only screen and (max-height: 700px)
@media only screen and (max-height: 600px)
@media only screen and (max-height: 380px)

@media print

**Comment by JohnCashmore** [comment]
Looks good to me this, one commit and you've already improved this this plugin massively :)
