### ISSUE TITLE
Add yuicompress option

### ISSUE THREAD

**Issue by spacedawwwg** [buildingblocks/grunt-combine-media-queries#17]
Option to compress re-formatted code (currently need to use something like grunt-contrib-cssmin to minfy CSS)

**Comment by stef-rausch** [comment]
Isn't your request out of scope?

**Comment by spacedawwwg** [comment]
Why would you think it is out of scope?

**Comment by stef-rausch** [comment]
The main objective of the plugin is to combine media queries and not to "compress" the `CSS` file — I do admit that combining is a sort of reducing the file size though.

**Comment by spacedawwwg** [comment]
I am going to develop the contrib to work for this situation:

```
less: {
    main: {
        options: {
            yuicompress: true
        },
        files: {
            'dist/css/main.css': 'src/less/_order.less'
        }
    }
},
cmq: {
    main: {
        options: {
            yuicompress: true
        },
        files: {
            'dist/css/': 'dist/css/main.css'
        }
    }
}
```

**grunt-combine-media-queries** should be an optional helper to preprocessors, so I'd like it to mimic some of the options they use.

**Comment by thomasdobber** [comment]
I agree with @StefanoRausch, it goes against the single responsibility principle. The right solution for the situation you described above would be to use a separate plugin for minification.

**Comment by spacedawwwg** [comment]
I think I might be able to 'have my cake and eat it' by default if we switch to 'postcss' instead of 'css-parse' (which you mentioned in another issue, Thomas) as it can maintain formatting (Though, I haven't looked at 'postcss' properly yet so I'm not 100% sure)

**Comment by serialpark** [comment]
maybe not a option to compress, but an option to keep the current output style.

**Comment by thomasdobber** [comment]
We are currently looking into using PostCSS, which would take care of the issue @spacedawwwg is experiencing.
