### ISSUE TITLE
Move core to separate module/repo

### ISSUE THREAD

**Issue by thomasdobber** [buildingblocks/grunt-combine-media-queries#20]
This plugin should only be a wrapper for Grunt. When we wrote grunt-combine-media-queries at the time I didn't realise this. I've been thinking about moving this thing to gulp (since that is my tool of choice now), but by moving the core to a separate module it can easily be used for e.g. Rework as well and it would be much easier to keep it up to date everywhere.

I will create an NPM module from the dev branch in a separate repo and start testing it.

I saw that somebody used our code to create a gulp plugin already and this is where the trouble begins...

**Comment by spacedawwwg** [comment]
I think we could start up a completely separate repo for this new module.

combinemq, grunt-combinemq, gulp-combinemq

This way we can completely start afresh but allow people using the current
grunt plugin to continue doing so.

What do you think?

Have you looked at postcss at all? I was hoping to try it out instead of
css-parse.

**Comment by thomasdobber** [comment]
Sorry Paul, I totally misread your comment!

I've been looking into both postcss and [node-css-mqpacker](https://github.com/hail2u/node-css-mqpacker) and came to the conclusion that postcss is awesome(!) and that mqpacker does exactly the same as grunt-combine-media-queries minus the ordering.

I suggest we open an issue on mqpacker and offer our help on improving it and if it turns out that they have no interest in such a function we can always start over. 

What do you think?

Ps. either way I have a couple of ideas for new modules that I would love to discuss with you guys if you are interested.
