### ISSUE TITLE
"@-moz-document" is not properly handled

### ISSUE THREAD

**Issue by luixxiul** [buildingblocks/grunt-combine-media-queries#21]
I think the media queries are not handled properly like this case:

```
@-moz-document url-prefix(http://www.example.com) {
  @media (min-width: 767px) {
    p {
      height: 5px;
    }
  }
}
```

**Comment by rastersysteme** [comment]
+1

I need it for this: https://gist.github.com/joaocunha/6273016#comment-1244649

**Comment by gijsroge** [comment]
Confirmed

**Comment by spacedawwwg** [comment]
This has now been added (also supporting nested media queries inside (at)document
