### ISSUE TITLE
Output Style Options

### ISSUE THREAD

**Issue by BHouwens** [buildingblocks/grunt-combine-media-queries#23]
Is there any chance of CSS output types being built into the options? Would love to be able to minify as I'm combining all in one task instead of running another afterwards.... now that I type this I feel like I'm becoming too lazy

**Comment by JohnCashmore** [comment]
I'd suggest that is the power of grunt tasks that you can run any number of tasks to do what you want and that it shouldn't be part of this task to do things like minifcation.

**Comment by BHouwens** [comment]
Fair enough. I just wondered; like I said I think things like Grunt are making me lazier XD
