### ISSUE TITLE
@charset is removed

### ISSUE THREAD

**Issue by okc37** [buildingblocks/grunt-combine-media-queries#24]
The line include `@charset` is removed.
 like https://github.com/buildingblocks/grunt-combine-media-queries/issues/13

```
@charset "UTF-8"
body {
    margin:0;
}
```

->

```
body {
    margin:0;
}
```

**Comment by losbeekos** [comment]
@keyframes and its vendor prefixes are removed too.

```
@keyframes animation {
}
```
