### ISSUE TITLE
Warning: Cannot find module 'css-parse' Use --force to continue.

### ISSUE THREAD

**Issue by voigtan** [buildingblocks/grunt-combine-media-queries#3]
When I'm trying to run the task I get the following error message:

Warning: Cannot find module 'css-parse' Use --force to continue.

I tried to run npm install css-parse --save-dev and rerun the task then I get this message:

Warning: Cannot call method 'join' of undefined Use --force to continue.

my config looks like:

```
cmq: {
    options: {
        log: false
    },
    your_target: {
      files: {
        '<%=compass.build.options.cssDir%>/mqsort': ['<%=compass.build.options.cssDir%>/*.css']
      }
    }
}
```

**Comment by spacebeers** [comment]
I'm having the exact same issue. I've updated Grunt to 0.4.1 and still no luck. Trying to debug it myself so I'll let you know if I can sort it out.

**Comment by JohnCashmore** [comment]
Hey,

Sorry about that there was an issue with the package.json that has now been fixed, if you update to the latest version you should have no issues.

Thanks
John

**Comment by spacebeers** [comment]
Thanks @JohnCashBB for the quick response. I'm getting the same issue still. I've updated to 1.0.4 and even replaced the package.json with the new one. Am I missing something?

**Comment by JohnCashmore** [comment]
It should add it do it automatically, you could do `npm install css-parse`
but i'll investigate it and see what the issue is.
