### ISSUE TITLE
Compress CSS output option

### ISSUE THREAD

**Issue by hugodessomme** [buildingblocks/grunt-combine-media-queries#34]
Hello,

Can you add an option to compress output ?

Thank you,
Good plugin by the way,
Hugo.

**Comment by furzeface** [comment]
Hi @hugodessomme - this plugin was deprecated a few months back - if you use the [newer version](https://github.com/frontendfriends/grunt-combine-mq) it has that option as seen [here](https://github.com/frontendfriends/grunt-combine-mq#new-filename).

Thanks.
