### ISSUE TITLE
Combine HiDPI rules

### ISSUE THREAD

**Issue by kremalicious** [buildingblocks/grunt-combine-media-queries#8]
Media queries are also used to serve high DPI assets so combining them into one definition would be very welcome.

The current best practice is to use this snippet, like in [H5BP](https://github.com/h5bp/html5-boilerplate/issues/1127) and [WordPress](http://core.trac.wordpress.org/changeset/22629):

``` css
@media print,
  (-o-min-device-pixel-ratio: 5/4),
  (-webkit-min-device-pixel-ratio: 1.25),
  (min-resolution: 120dpi) { }
```

**Comment by thomasdobber** [comment]
At the moment, the media queries are being sorted by min-width, max-width, min-height, max-height, others and at the very last print. That snippet should end up somewhere at the very end of the file. I am working on a way to make the sorting order and output order customisable in the options.

**Comment by kremalicious** [comment]
Thanks and indeed, that's working as expected. Probably too much caching going on when I tested that the first time. That media query snippet shows up right at the end and, if present, before a print only media query.
